I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Scripts/chapter1 pretunnel.rpy", line 28, in script
    show bgcafesepia alpha 0.5
Exception: Image 'bgcafesepia' does not accept attributes 'alpha 0 .5'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Scripts/chapter1 pretunnel.rpy", line 28, in script
    show bgcafesepia alpha 0.5
  File "C:\Renpy\renpy-8.0.0-sdk\renpy\ast.py", line 1388, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Renpy\renpy-8.0.0-sdk\renpy\ast.py", line 1351, in show_imspec
    renpy.config.show(name,
  File "C:\Renpy\renpy-8.0.0-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Renpy\renpy-8.0.0-sdk\renpy\display\image.py", line 413, in find_target
    self.target = target._duplicate(a)
  File "C:\Renpy\renpy-8.0.0-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "C:\Renpy\renpy-8.0.0-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'bgcafesepia' does not accept attributes 'alpha 0 .5'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.0.22062402
Erasers 1.0
Tue Jun 13 20:39:43 2023
