I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 485, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 485, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 509, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
PicklingError: Can't pickle <class 'store.mob'>: it's not the same object as store.mob

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00keymap.rpy", line 485, in script
    python hide:
  File "C:\Users\rkski\Documents\renpy-8.1.0-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\rkski\Documents\renpy-8.1.0-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 485, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 509, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "C:\Users\rkski\Documents\renpy-8.1.0-sdk\renpy\loadsave.py", line 427, in save
    reraise(t, e, tb)
  File "/home/tom/ab/nightly-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\rkski\Documents\renpy-8.1.0-sdk\renpy\loadsave.py", line 413, in save
    dump((roots, renpy.game.log), logf)
  File "C:\Users\rkski\Documents\renpy-8.1.0-sdk\renpy\compat\pickle.py", line 103, in dump
    pickle.dump(o, f, pickle.HIGHEST_PROTOCOL if highest else PROTOCOL)
PicklingError: Can't pickle <class 'store.mob'>: it's not the same object as store.mob

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23052503+nightly
Erasers 1.0
Tue Jun 27 17:21:40 2023
